// apps/react-app/src/App.tsx
import { useState } from 'react'

import './App.css'

import { MyInputCustomEvent } from '@stencil-ui/stencil'
import { MyComponent, MyHeading, MyInput, MyText } from '@stencil-ui/react'

function App() {
  const [name, setName] = useState('')

  function handleChangeName({ detail: value }: MyInputCustomEvent<string>) {
    setName(value)
  }

  return (
    <div className="App">
      <MyHeading>Vite + React + Web components</MyHeading>

      <MyText>Type your name:</MyText>

      <MyInput placeholder='Type...' onChangeInput={handleChangeName} />

      { name && <MyComponent name={name} /> }
    </div>
  )
}

export default App

// apps/vue-app/src/App.vue
<script setup lang="ts">
import { MyComponent, MyHeading, MyText, MyInput } from "@stencil-ui/vue"
</script>

<template>
  <main class="app">
    <MyHeading>Vue + Web components</MyHeading>

    <MyText>Type your name:</MyText>

    <MyInput placeholder='Type...'  />

    <MyComponent />
  </main>
</template>

<style scoped>
.app {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;

  background-color: #242424;

  min-height: 100vh;
  min-width: 100vw;
}

#my-component {
  margin-top: 10px;
}
</style>
