// apps/react-app/src/App.tsx
import { useState } from 'react'

import './App.css'

import { MyInputCustomEvent } from '@stencil-ui/stencil'
import { MyComponent, MyHeading, MyInput, MyText } from '@stencil-ui/react'

function App() {
  const [name, setName] = useState('')

  function handleChangeName({ detail: value }: MyInputCustomEvent<string>) {
    setName(value)
  }

  return (
    <div className="App">
      <MyHeading>Vite + React + Web components</MyHeading>

      <MyText>Type your name:</MyText>

      <MyInput placeholder='Type...' onChangeInput={handleChangeName} />

      { name && <MyComponent name={name} /> }
    </div>
  )
}

export default App

// apps/angular-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  name = 'Angular';

  onInputChange = (event: any) => {
    const value = event.detail;

    this.name = value
  }
}

<main class="app">
  <my-heading>Angular + Web components</my-heading>

  <my-text>Type your name:</my-text>

  <my-input placeholder="Type..." (changeInput)="onInputChange($event)"></my-input>

  <div style="margin-top: 10px;">
    <my-component name={{name}}></my-component>
  </div>
</main>
